[package]
name = "chip-8"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
fastrand = "2.3.0"
minifb = "0.28.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
